apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{.Values.global.namespace}}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.POSTGRES_USER |b64enc }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD |b64enc }}
  POSTGRES_DB: {{ .Values.POSTGRES_DB |b64enc }}
