{{- define "common.registry" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: chub
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}

