apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels:
    app: "postgres"
    group: "db"
spec:
  storageClassName: {{ .Values.global.storageClass }}
  capacity:
    storage: {{ .Values.pvSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
   path: "/niccloud/postgresql"
