apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: {{.Values.global.namespace}}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvSize }}
