# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#namespace: service-cloud-dev

# Common Labels
labels:
  app: "frontend"

# Container Configs
image:
  repository: "shaikcoredge/frontend_sso"
  pullPolicy: IfNotPresent
  tag: "1.5"
replicas: "1"
httpPort: 5000
resources: |
  requests:
    cpu: 100m
    memory: 256Mi
tracing-enabled: false

env: |
  - name: VUE_APP_SOCKET_IO
    value: "https://servicesocketio.cloud.gov.in"
  - name: VUE_APP_API_URL
    value: "https://serviceapi.cloud.gov.in"

volumes: |
  - name: frotnendnginx
    configMap:
      name: frotnendnginx

volumeMounts: |
  - name: frotnendnginx
    mountPath: /etc/nginx/conf.d
