# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#namespace: service-cloud-dev

# Common Labels
labels:
  app: "admi-api"

# Container Configs
image:
  repository: "shaikcoredge/middleware_sso"
  pullPolicy: IfNotPresent
  tag: "1.5"
replicas: "1"
httpPort: 5000
resources: |
  requests:
    cpu: 100m
    memory: 256Mi
tracing-enabled: false

env: |
  - name: CONSOLE_PROXY
    value: "https://serviceconsole.cloud.gov.in"
  - name: SMTP_SERVICE_URL
    value: "servicecloud-smtp"
  - name: SMTP_SERVICE_PORT
    value: "25"
  - name: FROM_NAME
    value: "NIC Cloud Services"
  - name: FROM_EMAIL
    value: "noreply@cloud.gov.in"
  - name: FLASK_CONFIG
    value: "production"
  - name: DB_HOST
    value: "postgres"
  - name: DB_PORT
    value: "5432"
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_USER
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_DB
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: POSTGRES_PASSWORD
  - name: SMS_SERVICE_USERID
    valueFrom:
      secretKeyRef:
        name: sms
        key: SMS_SERVICE_USERID
  - name: SMS_SERVICE_USERPIN
    valueFrom:
      secretKeyRef:
        name: sms
        key: SMS_SERVICE_USERPIN

envFrom: |
  - secretRef:
      name: postgres
      optional: false
  - secretRef:
      name: sms
      optional: false
 
volumes: |
  - name: admin-swagger-ui
    configMap: 
      name: admin-swagger-ui

volumeMounts: |
  - name: admin-swagger-ui
    mountPath: /opt/www/app/templates 

