---
# Source: celery/templates/secrets.yaml
apiVersion: v1
data:
  POSTGRES_DB: bWlkZGxld2FyZV9wcm9kdWN0aW9uX2Ri
  POSTGRES_PASSWORD: TWlkZGxld2FyZUAwMTAxMjAxOQ==
  POSTGRES_USER: bWlkZGxld2FyZV91c2Vy
kind: Secret
metadata:
  name: postgres
  namespace: middleware
type: Opaque
---
# Source: celery/templates/secrets.yaml
apiVersion: v1
data:
  SMS_SERVICE_USERID: Y2xvdWRuaWMub3Rw
  SMS_SERVICE_USERPIN: MWJnOGpvcWo=
kind: Secret
metadata:
  name: sms
  namespace: middleware
type: Opaque
---
# Source: celery/templates/service.yaml
# service.yaml---
apiVersion: v1
kind: Service
metadata:
  name: celery
  namespace: middleware
  annotations:
  labels:
    app: celery
spec:
  selector:
    app: celery
  ports:
  - name: http
    port: 5000
    targetPort: 5000
---
# Source: celery/templates/deployment.yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: middleware
  labels:
    app: celery
spec:
  selector:
    matchLabels:
      app: celery
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        deployment-timestamp: "20220124130045"
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: chub.cloud.gov.in/service-cloud/middleware:v010720210720
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: CONSOLE_PROXY
              value: "http://serviceconsole.cloud.gov.in/postgres-cred"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: FLASK_CONFIG
              value: "production"
            - name: DB_HOST
              value: "postgres-h"
            - name: DB_PORT
              value: "5432"
            - name: SMS_SERVICE_USERID
              valueFrom:
                secretKeyRef:
                  name: sms
                  key: SMS_SERVICE_USERID
            - name: SMS_SERVICE_USERPIN
              valueFrom:
                secretKeyRef:
                  name: sms
                  key: SMS_SERVICE_USERPIN

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
