apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "114"
    field.cattle.io/creatorId: user-vfhfj
  creationTimestamp: "2020-04-22T14:34:58Z"
  generation: 118
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-service-cloud-celery
  name: celery
  namespace: service-cloud
  resourceVersion: "330326141"
  selfLink: /apis/apps/v1/namespaces/service-cloud/deployments/celery
  uid: 765e365a-ba36-468d-8e89-1ebc723dd322
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-service-cloud-celery
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-07-01T02:27:32Z"
        field.cattle.io/ports: '[[{"containerPort":5000,"dnsName":"celery","hostPort":0,"kind":"ClusterIP","name":"5000tcp02","protocol":"TCP","sourcePort":0}]]'
        workload.cattle.io/state: '{"":"c-pqbpb:m-adb50b185c48","YmJzLW0tY2xvdWQtY29tcHV0ZTM=":"c-pqbpb:m-adb50b185c48"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-service-cloud-celery
    spec:
      containers:
      - env:
        - name: CONSOLE_PROXY
          value: http://serviceconsole.cloud.gov.in
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: FLASK_CONFIG
          value: production
        envFrom:
        - secretRef:
            name: postgres
            optional: false
        - secretRef:
            name: sms
            optional: false
        image: chub.cloud.gov.in/service-cloud/middleware:v010720210720
        imagePullPolicy: Always
        name: celery
        ports:
        - containerPort: 5000
          name: 5000tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - relay.nic.in
        ip: 164.100.14.95
      - hostnames:
        - smsgw.sms.gov.in
        ip: 164.100.14.211
      - hostnames:
        - cloud.gov.in
        ip: 164.100.166.179
      imagePullSecrets:
      - name: chub
      nodeName: bbs-m-cloud-compute3
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-22T14:34:58Z"
    lastUpdateTime: "2021-07-01T02:27:39Z"
    message: ReplicaSet "celery-79d945c4b5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-07-28T01:12:19Z"
    lastUpdateTime: "2021-07-28T01:12:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 118
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1