# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#namespace: service-cloud-dev
# Common Labels
labels:
  app: "api"

# Container Configs
image:
  repository: "shaikcoredge/middleware"
  pullPolicy: IfNotPresent
  tag: "v010720210720"
replicas: "1"
httpPort: 5000
resources: |
  requests:
    cpu: 100m
    memory: 256Mi
tracing-enabled: false

env: |
  - name: SMTP_SERVICE_URL
    value: "servicecloud-smtp"
  - name: SMTP_SERVICE_PORT
    value: "25"
  - name: FROM_NAME
    value: "NIC Cloud Services"
  - name: FROM_EMAIL
    value: "noreply@cloud.gov.in"
  - name: FLASK_CONFIG
    value: "production"
  - name: DB_PORT
    value: "5432"
  - name: DB_HOST
    value: "postgres"
  - name: CONSOLE_PROXY
    value: "https://serviceconsole.cloud.gov.in"

volumes: |
  - name: swagger-ui
    configMap: 
      name: swagger-ui

volumeMounts: |
  - name: swagger-ui
    mountPath: /opt/www/app/templates 
