# Default values for service-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#namespace: service-cloud-dev

# Common Labels
labels:
  app: "console"

# Container Configs
image:
  repository: "shaikcoredge/consoleproxy"
  pullPolicy: IfNotPresent
  tag: "latest"
replicas: "1"
httpPort: 80
resources: |
  requests:
    cpu: 100m
    memory: 256Mi
tracing-enabled: false

volumes: |
  - name: console-conf
    configMap: 
      name: console-conf

volumeMounts: |
  - name: console-conf
    mountPath:  /etc/nginx/conf.d/
